package com.vw.eacontext.api;

import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

import org.springframework.stereotype.Service;

import com.vw.eacontext.dto.DiagramExportRequest;
import com.vw.eacontext.dto.ExportFile;
import com.vw.eacontext.dto.Frame;
import com.vw.eacontext.dto.GraphDto;
import com.vw.eacontext.dto.GraphEdge;
import com.vw.eacontext.dto.GraphNode;

/**
 * Renders an observation frame as a PlantUML {@code .puml} source file, which
 * Confluence renders natively via the PlantUML macro and which — being plain
 * text — diffs and reviews like code.
 *
 * <p>Unlike the draw.io export, no geometry is emitted: PlantUML lays the
 * diagram out itself. The caller's placements are still honoured as the
 * in-scope node set, so an active filter narrows this export the same way.</p>
 */
@Service
public class PlantUmlExportService {

    /** PlantUML element keyword per projected node type. */
    private static final Map<String, String> KEYWORDS = Map.of(
            "application", "component",
            // A placeholder for a missing application is still a component as far
            // as the diagram is concerned; its label carries the unresolved id.
            "applicationGhost", "component",
            "domain", "rectangle",
            "process", "usecase",
            "informationObject", "artifact");
    private static final String DEFAULT_KEYWORD = "rectangle";

    /**
     * @param graph   the projected frame to export
     * @param frame   the frame being exported (drives the file name and title)
     * @param request the caller's request; non-empty placements narrow the node set
     * @return the {@code .puml} file
     */
    public ExportFile toPlantUml(GraphDto graph, Frame frame, DiagramExportRequest request) {
        Set<String> inScope = request.placements().keySet();
        Map<String, String> aliases = aliasNodes(graph, inScope);

        StringBuilder puml = new StringBuilder();
        puml.append("@startuml\n");
        puml.append("' Generated by Context Cartography — ").append(frame.label()).append(" frame\n");
        puml.append("skinparam componentStyle rectangle\n");
        puml.append("skinparam shadowing false\n");
        puml.append("title ").append(sanitize(frame.label())).append(" landscape\n\n");

        for (GraphNode node : graph.nodes()) {
            String alias = aliases.get(node.id());
            if (alias == null) {
                continue;
            }
            puml.append(KEYWORDS.getOrDefault(node.type(), DEFAULT_KEYWORD))
                    .append(" \"").append(sanitize(label(node)))
                    .append("\" as ").append(alias).append('\n');
        }

        puml.append('\n');
        for (GraphEdge edge : graph.edges()) {
            String source = aliases.get(edge.source());
            String target = aliases.get(edge.target());
            if (source == null || target == null) {
                continue;
            }
            // Mirrors the on-screen convention: the softer USES dependency and a
            // flow-only coupling are both dashed; declared dependencies are solid.
            boolean dashed = "USES".equals(edge.type()) || "FLOW".equals(edge.type());
            puml.append(source).append(dashed ? " ..> " : " --> ").append(target);
            if (edge.label() != null && !edge.label().isBlank()) {
                puml.append(" : ").append(sanitize(edge.label()));
            }
            puml.append('\n');
        }

        puml.append("@enduml\n");
        return new ExportFile("ea-context-" + frame.slug() + ".puml", "text/plain",
                puml.toString().getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Maps in-scope node ids to PlantUML-legal aliases ({@code APP-0001} ->
     * {@code APP_0001}), keeping them unique if two ids normalize to the same
     * token. Returns only the nodes that are in scope, so callers can use a
     * {@code null} lookup as the "filtered out" test.
     */
    private Map<String, String> aliasNodes(GraphDto graph, Set<String> inScope) {
        Map<String, String> aliases = new LinkedHashMap<>();
        Set<String> used = new HashSet<>();
        for (GraphNode node : graph.nodes()) {
            if (!inScope.isEmpty() && !inScope.contains(node.id())) {
                continue;
            }
            String base = node.id().replaceAll("[^A-Za-z0-9_]", "_");
            if (base.isEmpty() || Character.isDigit(base.charAt(0))) {
                base = "n_" + base;
            }
            String alias = base;
            for (int suffix = 2; !used.add(alias); suffix++) {
                alias = base + "_" + suffix;
            }
            aliases.put(node.id(), alias);
        }
        return aliases;
    }

    /**
     * The node's label, prefixed with a lock marker for a Confidential/PII/PCI
     * information object ({@code GraphProjectionService.informationFlowView}
     * already computes {@code data.sensitive}). Flagged, not redacted — mirrors
     * the same marker in {@code DrawioExportService}.
     */
    private String label(GraphNode node) {
        String text = node.label() == null ? node.id() : node.label();
        return Boolean.TRUE.equals(node.data().get("sensitive")) ? "🔒 " + text : text;
    }

    /** Labels are emitted inside quotes on a single line, so neither may survive. */
    private String sanitize(String text) {
        return text.replace('"', '\'').replaceAll("\\s+", " ").trim();
    }
}
